name: is_search
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  provider: ^6.1.1
  rename: ^3.0.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png

android_12:
  icon_background_color: "#FFFFFF"
  image: assets/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/